# Generated by Django 6.0.5 on 2026-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_name',
            field=models.CharField(blank=True, help_text='Nome exato do teste no sistema de laudos (ex: WISC-V)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_quantity',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
