# Generated by Django 6.0.5 on 2026-05-26 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('finished', 'Finalizado'), ('canceled', 'Cancelado'), ('no_show', 'Falta')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('is_telemedicine', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='core.clinic')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário Bloqueado',
                'verbose_name_plural': 'Horários Bloqueados',
            },
        ),
    ]
