# Generated by Django 6.0.5 on 2026-05-26 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='content',
        ),
        migrations.AddField(
            model_name='report',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('sections_snapshot', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.report')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Versão do Laudo',
                'ordering': ['-version_number'],
            },
        ),
    ]
