# Generated by Django 6.0.5 on 2026-05-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_content_remove_reporttemplate_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assessment_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/assessments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='report',
            name='selected_tests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='test_scores',
            field=models.JSONField(default=dict),
        ),
    ]
