# Generated by Django 6.0.5 on 2026-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_assessment_file_report_selected_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
