# Generated by Django 6.0.5 on 2026-05-26 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeurotestScale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scoring_guide', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Escala Neuropsicológica',
                'verbose_name_plural': 'Escalas Neuropsicológicas',
            },
        ),
        migrations.CreateModel(
            name='NeurotestSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluído')], default='pending', max_length=15)),
                ('raw_score', models.FloatField(blank=True, null=True)),
                ('normalized_score', models.FloatField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurotest_sessions', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neurotest_sessions', to=settings.AUTH_USER_MODEL)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='neurotests.neurotestscale')),
            ],
            options={
                'verbose_name': 'Sessão de Teste',
                'verbose_name_plural': 'Sessões de Testes',
                'ordering': ['-created_at'],
            },
        ),
    ]
