# Generated by Django 6.0.5 on 2026-05-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('neurotests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neurotestscale',
            options={'ordering': ['name'], 'verbose_name': 'Escala Neuropsicológica', 'verbose_name_plural': 'Escalas Neuropsicológicas'},
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Sigla usada no laudo e no estoque (ex: WISC-V)', max_length=30),
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='age_range',
            field=models.CharField(blank=True, help_text='Ex: 6 a 16 anos', max_length=50),
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='application_time',
            field=models.CharField(blank=True, help_text='Ex: 60–90 min', max_length=50),
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='category',
            field=models.CharField(blank=True, choices=[('intelligence', 'Inteligência e Cognição'), ('memory', 'Memória e Aprendizagem'), ('attention', 'Atenção e Funções Executivas'), ('development', 'Desenvolvimento / TDAH'), ('autism', 'TEA / Neurodesenvolvimento'), ('personality', 'Personalidade e Projetivos'), ('neuropsych', 'Avaliação Neuropsicológica Geral'), ('other', 'Outro')], max_length=50),
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neurotest_scales', to='core.clinic'),
        ),
        migrations.AddField(
            model_name='neurotestscale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
